### ISSUE TITLE
Problem with Emulators with API 26+

### ISSUE THREAD

**Issue by AKJAW** [sergio-sastre/FontSizeTestRule#1]
Hello, I couldn't find any guidelines for issues so I'll just explain the problem I'm experiencing.

I have a Jetpack Compose project for which I want to try out Snapshot testing. I was following the README for the [RoadToEffectiveSnapshotTesting](https://github.com/sergio-sastre/RoadToEffectiveSnapshotTesting) project and created a parameterized test where the font changes. 

[Shot](https://github.com/pedrovgs/Shot) only supports API's 26+ to create a screenshot for composables. However when I tried using this TestRule on API 26, 28 and 30 the font did not change. Neither in my own project nor in the [RoadToEffectiveSnapshotTesting](https://github.com/sergio-sastre/RoadToEffectiveSnapshotTesting) one.

I'm not sure if this is a problem with my machine / emulators or the TestRule. I wasn't able to debug the TestRule because I only had access to the decompiled sources (maybe it would be possible to expose the source code through the library to make debugging easier?).

My current hack to change the font looks like this:
``` kotlin
@Before
fun setUp() {
    InstrumentationRegistry
        .getInstrumentation()
        .uiAutomation
        .executeShellCommand("settings put system font_scale ${data.fontScale.value}")
        .apply {
            Thread.sleep(2000)
            close()
        }
}

@After
fun tearDown() {
    InstrumentationRegistry
        .getInstrumentation()
        .uiAutomation
        .executeShellCommand("settings put system font_scale 1.0")
        .apply {
            Thread.sleep(1000)
            close()
        }
}
```

But this is only an temporary solution 😄

**Comment by sergio-sastre** [comment]
Hi @AKJAW ! Thanks for reporting this issue. 
Just to make sure that I understood it right. You were not able to change the font size with FontSizeRule with the current code of the RoadToEffectiveSnapshotTesting project, or you cloned the repo, add your Composable components into and the FontSizeRule did not work with those Views?

I can tell you that I could not get Jetpack Compose 1.X.X working with Shot yet (probably something wrong on my side), so I could not really test this TestRule with Jetpack Compose, I suppose that might be the issue.

In order to let me investigate this issue, I recommend :
1) fork this repo
2) add your code into the androidTest package. You will also need to configure Shot though
3) make a PR to merge into this repo

That way we can probably debug it :)

**Comment by AKJAW** [comment]
Sorry for the confusion, the issue happens on the master branch of the RoadToEffectiveSnapshotTesting project.

When I run the tests on API 23 I get:
![com example road to effective snapshot testing parameterized AllDeleteDialogSnapshotTest_DARK_HUGE](https://user-images.githubusercontent.com/26874608/131848658-f49d194d-94cb-48a7-90b0-5ac5016bfc81.png)

However when running it on API 26 I get:
![com example road to effective snapshot testing parameterized AllDeleteDialogSnapshotTest_DARK_HUGE](https://user-images.githubusercontent.com/26874608/131848719-f48d8ba5-5730-4185-9bf4-c1192323dea1.png)

The only change in the repository is a the "largest" string in strings.xml

**Comment by sergio-sastre** [comment]
@AKJAW Yep, you are right and I know why.
This TestRule is simulating the "font size" by calling `resource.updateConfiguration(resources.configuration, metrics)`. However that methods deprecated since API 25 or 26, and the alternative, `context.createConfigurationContext()` requires to override the Activity's `attachBaseContext()` method, and therefore it cannot be encapsulated in a testRule like this.

The proposed method actually does not work.
Your workaround works indeed because it really changes the fontSize of the device via adb. However, that requires some time for the change to become effective. That is exactly the approach that Novoda used in their Espresso-support [FontScaleSetting.java](https://github.com/novoda/espresso-support/blob/master/core/src/main/java/com/novoda/espresso/FontScaleSetting.java), checking every X seconds whether the fontScale already became effective. I found out it worked most of the times but in some old devices (some with API 21 or lower if I recall correctly) the fontSize change never became effective. Moreover, this makes Snapshot tests slower.

Therefore, I would suggest to take novodas approach for devices targeting API 25 or 26 on.

I will make a pre-release in the following days with these changes in order to test it properly ;)

**Comment by AKJAW** [comment]
Great, thanks for the quick reaction and the background info 😄 Shame about the test rule, like you said, the adb way is much slower

**Comment by sergio-sastre** [comment]
Hi @AKJAW !
I think I found a nice workaround. Moreover, no testRule is necessary for that, but an Activity Scenario "wrapper".

You can find the solution in this [PR](https://github.com/sergio-sastre/FontSizeTestRule/pull/3).
I'll try to publish a release in the following days and update the "RoadToEffectiveSnapshotTesting" repo with the corresponding samples. However, you can try to copy paste it in the meanwhile.

**Comment by sergio-sastre** [comment]
Regarding Composable:
For now , I am afraid one should use the `FontSizeTestRule` , i.e.  the adb command approach, which is slower. That's because composable do not require `Activity`'s context, but I need to give it a try. However, I wonder if one could use a similar approach to that of `ActivityScenario`: Create an extension of `createAndroidComposeRule<YourActivity>()` to get it working. I still need to get my head around it though ;)

**Comment by sergio-sastre** [comment]
I'll close the issue. 
You can use v.1.1.0-SNAPSHOT to solve the problem
Please feel free to re-open it if it does not solve your issue :)
